### PR TITLE
Various improvements including Elli Charger Connect/Pro support

### PR DESCRIPTION
**Pull request by DerAndereAndi**
This contains various improvements:

- If the heartbeat returns an error, close the connection so a new one can be established which may fix the problem
- Support for coordinated charging via ISO
- Use the proper SPINE version in the messages
- Various additions to support Elli Charger Connect/Pro
- Switch to libp2p/zeroconf for mDNS with fix for avahi 0.8-pr1 compatibility
- Fix heartbeat missing timestamp
- Workaround for Elli charger disconnecting if there is no EV connected for 10 minutes

### CODE REVIEW

**Comment by andig** [comment]
Ich hab auf Go 1.18 umgestellt- thoas fliegt raus und es gibt weniger neue dependencies.

**Comment by DerAndereAndi** [comment]
Fixes https://github.com/evcc-io/eebus/issues/3

The latest commit provides a workaround for this issue.

**Comment by DerAndereAndi** [comment]
The current state seems to be working for me. The certificate issue is still pending and some special workaround are still needed. Hopefully a future update of the Elli firmware will remove the need for them.

**Comment by DerAndereAndi** [comment]
@andig Ready for merge from my end.

**Comment by andig** [comment]
Danke. Ich hab die Commit Message weg gelassen da nicht mehr klar war, was davon noch gilt- wenn Du magst kann ich noch eine nachschieben.

**Comment by DerAndereAndi** [comment]
@andig stimmt, hatte ich nicht geschaut. Hab die Messge hier aktualisiert.

**Comment by andig** [comment]
Done- vielen Dank!

**Pull request merged**
